DEFAULT_PORT = 8765
DEFAULT_MODE = "mock"
DEFAULT_MOCK_EVENTS_PER_SECOND = 0.1
DEFAULT_DATABASE_PATH = "./noema_bridge.sqlite3"
DEFAULT_RING_BUFFER_SIZE = 500
DEFAULT_DEDUPE_WINDOW_SECONDS = 30.0
DEFAULT_LIVE_OFFLINE_POLL_SECONDS = 60.0
DEFAULT_EXTERNAL_TTS_MODEL = "tts-1"
